Repository bigbio/quantms-rescoring, pull requests merged in 2025-03, with the labels that each got.

#19 removed printed pyopenms warning
  quantmsrescore/openms.py
Labels: Review effort 1/5

#18 major patch for ms2pip to use pyopenms instad of ms2rescore-rs
  .github/workflows/python-app.yml
  .github/workflows/python-package.yml
  README.md
  environment.yml
  pyproject.toml
  quantmsrescore/__init__.py
  quantmsrescore/annotator.py
  quantmsrescore/deeplc.py
  quantmsrescore/idxmlreader.py
  quantmsrescore/logging_config.py
  quantmsrescore/ms2pip.py
  quantmsrescore/ms2rescore.py
  quantmsrescore/openms.py
  quantmsrescore/sage_feature.py
  quantmsrescore/snr.py
  recipe/meta.yaml
  tests/test_commands.py
  tests/test_openms.py
Labels: Review effort 4/5

#20 Improve logging, multithreads and remove decoy flags and default similarity threshold from 0.8 -> 0.7
  .github/workflows/python-app.yml
  pyproject.toml
  quantmsrescore/__init__.py
  quantmsrescore/annotator.py
  quantmsrescore/idxmlreader.py
  quantmsrescore/logging_config.py
  quantmsrescore/ms2pip.py
  quantmsrescore/ms2rescore.py
  quantmsrescore/openms.py
  quantmsrescore/rescoring.py
  recipe/meta.yaml
  tests/test_commands.py
Labels: Review effort 3/5
